/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reproductor_musica;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author adria
 */
public class Repro extends javax.swing.JFrame {
          File archivo;
          Clip clip;
          
    /**
     * Creates new form Repro
     */
    public Repro() {
        super("Reproductor de musica");
        initComponents();
        btnPlay.setIcon(new ImageIcon("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\com\\mycompany\\reproductor_musica\\iconos\\352074_circle_play_icon.svg"));
        btnPause.setIcon(new ImageIcon("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\com\\mycompany\\reproductor_musica\\iconos\\352074_circle_play_icon.png"));
        //btnStop.setIcon(new ImageIcon("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\iconos\\detener.png"));
        //btnReset.setIcon(new ImageIcon("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\iconos\\reset.png"));
        btnPlay.setBackground(Color.WHITE);
        btnPlay.setBorder(null);
         btnPause.setBackground(Color.WHITE);
        btnPause.setBorder(null);
         btnStop.setBackground(Color.WHITE);
        btnStop.setBorder(null);
         btnReset.setBackground(Color.WHITE);
        btnReset.setBorder(null);
        
        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textNameSong = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        comboMusica = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textNameSong.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        textNameSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameSongActionPerformed(evt);
            }
        });

        btnPlay.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPause.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnPause.setForeground(new java.awt.Color(255, 255, 255));
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnStop.setForeground(new java.awt.Color(255, 255, 255));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        comboMusica.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        comboMusica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dua Lipa - Break My Heart", "Rammstein - Du Hast", "Carmen Sarahí - Libre soy", " ", " " }));
        comboMusica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMusicaItemStateChanged(evt);
            }
        });
        comboMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMusicaMouseClicked(evt);
            }
        });
        comboMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMusicaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reproduciendo");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel2.setText("Selecciona una cancion");

        btnOk.setBackground(new java.awt.Color(51, 255, 0));
        btnOk.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Aceptar");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(textNameSong, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPause)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnStop))
                            .addComponent(jLabel2))
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboMusica, 0, 1, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOk)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNameSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnPause)
                    .addComponent(btnReset)
                    .addComponent(btnStop))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameSongActionPerformed

    private void comboMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMusicaActionPerformed
                
    }//GEN-LAST:event_comboMusicaActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        
        textNameSong.setText((String)comboMusica.getSelectedItem() );
        clip.start();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        clip.close();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        clip.stop();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try{
            if(textNameSong.getText().equals("")){
                cargarAudio();
            }
            else{
                clip.close();
                cargarAudio();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        
    }//GEN-LAST:event_btnOkMouseClicked

    private void comboMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMusicaMouseClicked
            
    }//GEN-LAST:event_comboMusicaMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clip.setFramePosition(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void comboMusicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMusicaItemStateChanged
       // textNameSong.setText((String)comboMusica.getSelectedItem() );
    }//GEN-LAST:event_comboMusicaItemStateChanged
    public void cargarAudio() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        switch(comboMusica.getSelectedIndex()){
            case 0:
                archivo = new File("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\com\\mycompany\\reproductor_musica\\Canciones\\Dua Lipa - Break My Heart (Official Video).wav");
                try{
                    controlAudio(archivo);
                }catch(Exception e){
                    e.printStackTrace();
                }
                break;
            case 1:
                archivo = new File("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\com\\mycompany\\reproductor_musica\\Canciones\\Rammstein - Du Hast (Official 4K Video).wav");
                try{
                    controlAudio(archivo);
                }catch(Exception e){
                    e.printStackTrace();
                }
                break;
            case 2:
                archivo = new File("C:\\Users\\adria\\Documents\\TAP\\Reproductor_Musica\\src\\main\\java\\com\\mycompany\\reproductor_musica\\Canciones\\Carmen Sarahí - Libre Soy (De ＂Frozen： Una Aventura Congelada＂⧸Con letra).wav");
                try{
                    controlAudio(archivo);
                }catch(Exception e){
                    e.printStackTrace();
                }
                break;
        }
    }
    
    public void controlAudio(File ruta) throws UnsupportedAudioFileException, IOException, LineUnavailableException    {
            AudioInputStream audio = AudioSystem.getAudioInputStream(ruta);
            clip = AudioSystem.getClip();
            clip.open(audio);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Repro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Repro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Repro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Repro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Repro().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStop;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboMusica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textNameSong;
    // End of variables declaration//GEN-END:variables
}
